package Utils;

import org.apache.log4j.*;

public class Log {

    public  static  Logger log = Logger.getLogger(Log.class.getName());


    // when my test stops, I should print the logs
    // if I want to print any message in between, I should print the logs

    // when the test starts, I should print the logs
    public static void startTestCase(String testCaseName){
        log.info("**");
        log.info("**");
        log.info("*********"+ testCaseName + "*********");

    }
    public  static void endTestCase(String testCaseName){

        log.info("#######################");
        log.info("#######################");
        log.info("###########"+ testCaseName+"############");
    }
    public static void info(String message){
        log.info(message);
    }
    public  static void warning(String warning)
    {
        log.info(warning);
    }

    // ===================MAVEN LIFECYCLE============================

    // Maven Life Cycle: thi consists of several phase
    // clean: Removes all the files generated by the previous build
    //Validate: checks the project is correct and all the necessary information is available
    // 3- Compile: compiles the source code of the project
    // Test: runs the testcase for the project
    // package: packages the compiled code into a distributable format, such as JAR or WAR files
    // verify : runs and checks on result of integration tests to ensure quality criteria is met
    // install: installs the packages into local repository
    // site: generates documentations for the project
    // deploy: copies the final package to remote repository for sharing with other developers or projects






//*In software engineering, a WAR file is a file used to distribute a collection of JAR-files, JavaServer Pages,
// Java Servlets, Java classes, XML files, tag libraries, static web pages and other resources that together
// constitute a web application.*
}
